log_learning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')), #use the argument namespace if you working with only one app
    path('', include('log_learnings.urls')),
]

log_learnings/urls.py
from django.urls import path
from . import views

app_name = 'log_learnings'


urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),#u can acess (users:login) because of this
    path('register/', views.register, name='register'),

]

log_learnings/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=120)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('log_learnings:topic', args=[self.id])


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField() #separted the textfield sekof we want entry to be optional
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f'{self.text[:50]}...'
#% url 'log_learnings:topic' topic.pk %

users/models.py
from django.db import models

# Create your models here.

log_learnings/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

log_learnings/views.py
from django.shortcuts import render, redirect
from .models import Topic,Entry
from . forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

def index(request):
    return render(request, 'index.html')


@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    return render(request, 'topics.html', {'topics': topics})


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    return render(request, 'topic.html', {'topic': topic, 'entries': entries})


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('log_learnings:topics')

    return render(request, 'new_topic.html', {'form': form})


@login_required
def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('log_learnings:new_entry', topic_id=topic_id)
    return render(request, 'new_entry.html', {'topic': topic, 'form':form})


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('log_learnings:topic', topic_id=topic.id)

    return render(request, 'edit_entry.html', {'entry': entry, 'topic': topic, 'form': form})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('log_learnings:index')
        
    return render(request,'registration/register.html', {'form': form})
            

templates/base.html
{% load bootstrap4 %}
<! doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
       shrink-to-fit=no">
<title>Learning Log</title>
    {%bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'log_learnings:index'%}"> Learning Log</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span></button>
 <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'log_learnings:topics'%}">
              Topics</a></li>
      </ul>
<ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text"}">Hello, {{ user.username }}.</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
<main role="main" class="container">
 <div class="pb-2 mb-2 border-bottom">
         {% block page_header %}{% endblock page_header %}
       </div>
 <div>
{% block content %}{% endblock content %}
       </div>
     </main>
   </body>
   </html>
</body>
</html>

templates/edit_entry.html
{% extends 'base.html' %}
{% block content %}

<p><a href="{% url 'log_learnings:topic' topic.id %}">{{ topic }}</a></p>



<p>Edit entry:</p>

    <form action="{%url 'log_learnings:edit_entry' entry.id %}" method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <button name="submit"> Save Entry </button>

</form>


{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block page_header %}
<div class="jumbotron">
<h1 class="display-3">Track your learning.</h1>
<p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about. Whenever you learn something new about a topic, make an entry summarizing what you've learned.</p>
<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
</div>
{% endblock page_header %}

templates/new_entry.html
{% extends 'base.html' %}
{% block content %}

<p><a href="{% url 'log_learnings:topic' topic.id %}">{{ topic }}</a></p>
<p>Add a new entry:</p>
<form action="{%url 'log_learnings:new_entry' topic.id %}" method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <button name="submit">Save Entry</button>
</form>






{% endblock content %}

templates/new_topic.html
{% extends 'base.html' %}
{% block content %}

<p> New Topic </p>

<form action="{% url 'log_learnings:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add new topic</button>
</form>

{% endblock content %}

templates/topic.html
{% extends 'base.html' %}

{% block page_header %}
<h3>{{ topic }}</h3>
   {% endblock page_header %}
{% block content %}
<p>
    <a href="{% url 'log_learnings:new_entry' topic.id %}">Add new entry</a>
</p>
<ul>
    {% for entry in entries %}
<div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'log_learnings:edit_entry' entry.id %}">
            edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>

    {% empty %}
    <p> No entry updated for this biko</p>
{% endfor %}
</ul>









{% endblock content %}

templates/topics.html
{% extends 'base.html' %}
{% block content %}
{% block page_header %}
<p>Topics</p>
{% endblock page_header %}
<ul>
{% for topic in topics %}
    <li><h3> <a href="{{topic.get_absolute_url}}"> {{ topic }} </a> </h3></li>
    {% empty %}
   <li><h3>  No topics added yet </h3></li>
{% endfor %}
</ul>
<h3><a href="{% url 'log_learnings:new_topic' %}">Add a new topic</a></h3>
{% endblock content %}